# Generated by Django 4.2.17 on 2024-12-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
